name: Automated changelog
description: Automated Fondeadora mobile app changelog 🚀

inputs: 
  release_tag:
    description: Release tag version
  slack_channel:
    description: App changelog slack channel
  github_key:
    description: Fondeadora app github key
  graphql_schema:
    description: GraphQL Schema
  slack_token:
    description: Slack api token

runs:
  using: node16
  main: index.js 