name: Automated changelog
description: Automated Fondeadora mobile app changelog 🚀

inputs: 
  release_tag:
    description: Release tag version
    required: true
  slack_channel:
    description: App changelog slack channel
    required: true
  github_key:
    description: Fondeadora app github key
    required: true
  slack_token:
    description: Slack api token
    required: true

runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Run changelog automation
      env: 
        CHANNEL: ${{ github.event.inputs.slack_channel }}
        GITHUB_KEY: ${{ github.event.inputs.github_key }}
        RELEASE_TAG: ${{ github.event.inputs.release_tag }}
        SLACK_TOKEN: ${{ github.event.inputs.slack_token }}
      run: |
        yarn install
        node index.js
      shell: bash